name: CI - Tests et validation

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration du python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.1

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-flask bandit safety

      - name: SAST - Scan Bandit
        run: |
          echo "Bandit scan started (Static Analyse Tool)"
          bandit app.py -f screen
          bandit app.py -f json -o bandit-report.json

      - name: SCA - Scan Safety
        env:
          SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
        if: always()
        run: |
          echo "Safety scan started (Depandancies scan Tool)"
          safety scan -r requirements.txt --full-report
          safety scan -r requirements.txt --json > safety-report.json

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: secdevopsbank:${{ github.sha }}
          load: true
          cache-from: type-gha
          cache-to: type=gha,mode=max

      - name: Scan Trivy
        uses: aquasecurity/trivy-action@master # https://github.com/aquasecurity/trivy-action#uses
        with:
          image-ref: "secdevopsbank:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          severity: "CRITICAL,HIGH"

      - name: Execution des tests
        run: |
          cd tests
          pip install pytest
          pytest test_app.py -v

      - name: Rapport des tests
        if: always()
        run: |
          echo "tests terminés"
          echo "Consultez les logs ci-dessus pour les détails"

      - name: Upload des rapports de securité
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit-report.json
            safety-report.json

      - name: 🔍 Vérification de la structure du projet
        run: |
          echo "📁 Structure du projet:"
          ls -la
          echo ""

      - name: Afficher des informations
        run: |
          echo "Pipeline executed with success"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Branch: ${{ github.ref }}"
